name: Deno Cross-Compilation and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          #- x86_64-apple-darwin
          #- x86_64-pc-windows-msvc
          #- aarch64-apple-darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Compile for ${{ matrix.target }}
        run: deno compile --allow-net --target ${{ matrix.target }} home-tunnel.ts

      - name: Copy executable and assets
        run: |
          mkdir package
          mv -v home-tunnel package/
          cp -v install_service.sh package/
          cp -v home-tunnel.service.template package/

      - name: Package into archive
        run: |
          tar -czvf hometunnel-${{ matrix.target }}.tar.gz package/*
          rm -rf package
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: home-tunnel-${{ matrix.target }}
          path: hometunnel-${{ matrix.target }}.tar.gz
          if-no-files-found: error
